import { useEffect, useRef } from "react";
import type { SlideData, ThemeSettings } from "../lib/types";
import { handleSmartPaste } from "../lib/richPaste";
import {
  DEFAULT_PLAIN_NUMBERING,
  plainNumberingDef,
  effectiveOptionLabel,
  autoOptionKey,
  resetOptionLabels,
  hasManualOptionLabels,
} from "../lib/plainNumbering";
import { FONT_BY_FAMILY, ensureFontStylesheet } from "../lib/fonts";
import { boxFontLabel, elementInk, setBoxFont, setElementInk } from "../lib/boxFonts";
import FontPicker from "./FontPicker";
import OptionStylePicker from "./OptionStylePicker";
import { Btn, ColorInput, Field, SegButtons, Slider, TextInput } from "./ui";
import { cn } from "../utils/cn";

/**
 * Navigation ▸ "Option text".
 *
 * Everything about the choices block on a slide: the choices themselves
 * (add / edit / remove / labels, and which one is correct), how the option
 * ROWS look (container style, column layout, gap) and the option text's own
 * typography. The markers' shape/colour live in "Option bullet", the letters
 * inside them in "Opt bullet text", and deck-wide answer actions (reveal all,
 * answer copies) in "Answer key".
 */
interface Props {
  slide?: SlideData;
  theme: ThemeSettings;
  setTheme: (p: Partial<ThemeSettings>) => void;
  updateSlide: (id: string, p: Partial<SlideData>) => void;
  /** open the "text inside option bullet" panel (labels, ink and marker face) */
  onOpenBulletText?: () => void;
}

export default function OptionTextPanel({ slide, theme: T, setTheme, updateSlide, onOpenBulletText }: Props) {
  const refs = useRef<Record<number, HTMLInputElement | null>>({});
  /**
   * The style every AUTO label is generated from. An unknown/legacy value
   * resolves to "Default", which is exactly how the board treats it (no
   * numbering, option keys as they are) — so the panel can never disagree with
   * the slide.
   */
  const numberingDef = plainNumberingDef(T.plainNumbering ?? DEFAULT_PLAIN_NUMBERING);
  const currentNumbering = numberingDef.id;
  /**
   * The option face lives on the options box only (boxFonts.options) — writing
   * it to the deck's Bengali font would repaint every text box on the slide.
   * With no override the box still follows the deck Bangla font, so decks saved
   * before this was scoped keep rendering exactly as they did.
   */
  const optionFont = boxFontLabel(T, "options");

  // a deck can be saved with any face from the library — make sure the one it
  // uses is actually downloaded, not just listed in the picker
  useEffect(() => {
    const meta = FONT_BY_FAMILY.get(optionFont.toLowerCase());
    if (meta) ensureFontStylesheet([meta]);
  }, [optionFont]);

  if (!slide) return <p className="text-sm text-slate-500">No slide selected.</p>;

  return (
    <div className="space-y-4">
      <div className="border-b border-white/10 pb-3"><h2 className="text-base font-semibold text-slate-100">Option text</h2><p className="text-[11px] text-slate-500">The choices and the rows they sit in — edit, style and lay them out.</p></div>
      <div className="space-y-2">
        {slide.options.map((opt, i) => {
          const correct = slide.answer === opt.key;
          const displayLabel = effectiveOptionLabel(opt.labelMode, opt.key, currentNumbering, i);
          const manual = opt.labelMode === "manual";
          return (
            <div key={i} className="flex items-center gap-1.5">
              <button
                onClick={() => updateSlide(slide.id, { answer: correct ? null : opt.key })}
                title="Mark correct answer"
                className={cn("h-7 w-7 shrink-0 rounded-full border text-xs font-bold", correct ? "border-emerald-400 bg-emerald-400/20 text-emerald-300" : "border-white/15 text-slate-500")}
              >
                {correct ? "✓" : ""}
              </button>
              {/* label state: an AUTO label is painted by Plain Numbering and
                  follows it; a MANUAL one is pinned (tinted) and outranks the
                  style until "Reset Labels" releases it */}
              <input
                value={displayLabel}
                onChange={(e) => {
                  const newKey = e.target.value;
                  const options = slide.options.map((o, j) => j === i ? { ...o, key: newKey, labelMode: "manual" as const } : o);
                  updateSlide(slide.id, { options, answer: correct ? newKey : slide.answer });
                }}
                title={
                  manual
                    ? `Manual label — it outranks Plain Numbering (${numberingDef.label}). “Reset Labels” restores the generated one.`
                    : `Auto label — generated by Plain Numbering (${numberingDef.label}). Type here to override it for this option.`
                }
                className={cn(
                  "w-10 rounded-lg border px-1 py-2 text-center text-sm outline-none",
                  manual
                    ? "border-amber-400/50 bg-amber-400/10 text-amber-100"
                    : "border-white/10 bg-slate-900/70 text-amber-200",
                )}
              />
              <TextInput
                ref={(el) => { refs.current[i] = el; }}
                value={opt.text}
                placeholder={`Option ${i + 1}`}
                onPaste={(e) => {
                  const res = handleSmartPaste(e, { singleLine: true });
                  if (res) updateSlide(slide.id, { options: slide.options.map((o, j) => j === i ? { ...o, text: res.value } : o) });
                }}
                onChange={(e) => updateSlide(slide.id, { options: slide.options.map((o, j) => j === i ? { ...o, text: e.target.value } : o) })}
              />
              <button onClick={() => updateSlide(slide.id, { options: slide.options.filter((_, j) => j !== i) })} className="px-1.5 text-slate-500 hover:text-rose-300">✕</button>
            </div>
          );
        })}
        <div className="flex items-center gap-2">
          <Btn
            size="sm"
            onClick={() => {
              const nextIndex = slide.options.length;
              // the new option joins in AUTO mode, so it is born labelled by
              // whatever plain numbering the deck is set to
              const newKey = autoOptionKey(currentNumbering, nextIndex, slide.options[0]?.key ?? "");
              updateSlide(slide.id, { options: [...slide.options, { key: newKey, text: "", labelMode: "auto" }] });
            }}
          >
            + Add option
          </Btn>
          {/* one global reset for every label — individual rows stay untouched
              (they keep their ✕ delete button and their editable label field) */}
          <Btn
            size="sm"
            onClick={() => updateSlide(slide.id, resetOptionLabels(slide.options, slide.answer, currentNumbering))}
            title={
              hasManualOptionLabels(slide.options)
                ? "Clear all custom labels and go back to Plain Numbering"
                : "Regenerate every label from the current Plain Numbering"
            }
          >
            ↻ Reset Labels
          </Btn>
        </div>
      </div>
      {/* ------------------------- option rows & layout --------------------- */}
      <div className="space-y-3 rounded-xl border border-white/10 bg-white/[0.03] p-3">
        <div className="flex items-baseline justify-between">
          <span className="text-[11px] font-semibold tracking-wide text-slate-200 uppercase">Option rows & layout</span>
          <span className="text-[10px] text-slate-500">the container each choice sits in</span>
        </div>
        <Field label="Row container style" hint="24 styles" as="div">
          <OptionStylePicker theme={T} setTheme={setTheme} />
        </Field>
        <Field label="Options layout">
          <SegButtons
            value={T.optionsLayout}
            onChange={(v) => setTheme({ optionsLayout: v })}
            options={[
              { value: "right", label: "Right" },
              { value: "left", label: "Left" },
              { value: "two-col", label: "2 Col" },
              { value: "grid", label: "Grid" },
            ]}
          />
        </Field>
        <Field label="Gap between rows" hint={T.optionGap ? `${T.optionGap}%` : "auto"}>
          <Slider min={0} max={14} step={0.5} value={T.optionGap} onChange={(v) => setTheme({ optionGap: v })} />
        </Field>
      </div>

      {/* ------------------------- option text typography ------------------- */}
      <Field label="Option font size" hint={`${T.optionSize}px`}>
        <Slider min={16} max={46} value={T.optionSize} onChange={(v) => setTheme({ optionSize: v })} />
      </Field>
      <Field label="Wrapped text line height" hint={`${T.optionLineHeight}`}>
        <Slider min={1} max={2.2} step={0.05} value={T.optionLineHeight} onChange={(v) => setTheme({ optionLineHeight: v })} />
      </Field>
      <FontPicker
        label="Option text font"
        value={optionFont}
        previewTarget="box:options"
        onChange={(family) => {
          const meta = FONT_BY_FAMILY.get(family.toLowerCase());
          if (meta) ensureFontStylesheet([meta]);
          // patch the options box only (family, nothing else) — the deck's
          // Bengali/Latin/Arabic fonts and every other box stay untouched
          setTheme({ boxFonts: setBoxFont(T.boxFonts, "options", { family }) });
        }}
        script="all"
        compact
      />
      <div className="grid grid-cols-2 gap-2">
        <ColorInput label="Option text" value={elementInk(T, "options")} onChange={(v) => setTheme(setElementInk(T, "options", v))} />
      </div>
      {/* the label painted inside each marker is styled under "Opt bullet text" */}
      <div className="flex items-center justify-between gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2">
        <span className="text-[11px] leading-snug text-slate-400">
          Marker labels: <b className="text-slate-200">{numberingDef.label}</b>
          <span className="ml-1 text-slate-500">{numberingDef.example}</span>
        </span>
        {onOpenBulletText && (
          <button
            type="button"
            onClick={onOpenBulletText}
            className="shrink-0 text-[11px] font-medium text-amber-300 hover:underline"
          >
            Change →
          </button>
        )}
      </div>
      <p className="text-[10px] leading-relaxed text-slate-500">
        Tick a row to mark the correct answer. Deck-wide answer actions — reveal all, hide all, answer copies — live
        under <b>Answer key</b>.
      </p>
    </div>
  );
}